### ISSUE TITLE
PerWorldInventory

### ISSUE THREAD

**Issue by kiritss** [Prunt/RestrictedCreative#6] opened 2017-09-28 21:40 UTC
I use a plugin called PerWorldInventory in order to have a creative world. Having a creative world + perworldinventory with restrictedcreative really screws up the inventories and they often don't load properly

**Comment by Prunt** [comment] 2017-09-29 06:13
Can you be more specific? I need the exact steps to reproduce the problem, only then I can work out what is causing it.

**Comment by Prunt** [comment] 2017-11-01 10:09
Closing the issue due to no answer.

**Closed by Prunt** 2017-11-01 10:09 UTC
