### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SanjarTR** [Prunt/RestrictedCreative#10] opened 2018-01-02 11:56 UTC
```
[12:58:52] [Server thread/ERROR]: Could not pass event PlayerGameModeChangeEvent to RestrictedCreative v1.12.3
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7754231-94b0980]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7754231-94b0980]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-7754231-94b0980]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:1145) [spigot.jar:git-Spigot-7754231-94b0980]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setGameMode(CraftPlayer.java:798) [spigot.jar:git-Spigot-7754231-94b0980]
at com.earth2me.essentials.commands.Commandgamemode.run(Commandgamemode.java:68) [EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) [EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:511) [EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:424) [EssentialsX-2.0.1.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-7754231-94b0980]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-7754231-94b0980]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651) [spigot.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392) [spigot.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227) [spigot.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7754231-94b0980]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-7754231-94b0980]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: Cannot cast [Lorg.bukkit.inventory.ItemStack; to me.prunt.restrictedcreative.Main
at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361) ~[?:1.8.0_111]
at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356) ~[?:1.8.0_111]
at me.prunt.restrictedcreative.Main.creative(Main.java:712) ~[?:?]
at me.prunt.restrictedcreative.EventListener.onPlayerGameModeChange(EventListener.java:958) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-7754231-94b0980]
... 25 more
```

**Comment by Prunt** [comment] 2018-01-05 17:22
This really puzzles me: `Caused by: java.lang.ClassCastException: Cannot cast [Lorg.bukkit.inventory.ItemStack; to me.prunt.restrictedcreative.Main`
It has literally no reason to cast my Main class to an ItemStack. Computers are a mystery. :D

Anyway, I rewrote the troubling part and it should be more robust now. Wait for the next version. :)

**Comment by Prunt** [comment] 2018-01-05 22:12
1.12.4 is up! Test it out and let me know.

**Comment by Prunt** [comment] 2018-01-10 14:07
I'm closing the issue for now, let me know if the update didn't fix anything.

**Closed by Prunt** 2018-01-10 14:07 UTC
