### ISSUE TITLE
issues with restrictions & Questions

### ISSUE THREAD

**Issue by Syrkulous** [Prunt/RestrictedCreative#82] opened 2020-03-17 04:37 UTC
Creative players are able to place flowers and obtain them in survival.

How do I allow staff to bypass restrictions but have separated inventories?

**Comment by hankur** [comment] 2020-03-23 12:38
Duplicate of https://bitbucket.org/Prunt/restrictedcreative/issues/84/creative-placed-flowers-can-be-chipped-in

**Closed as completed by hankur** 2020-03-23 12:38 UTC
Labels: duplicate
