### ISSUE TITLE
Bug with lava bucket

### ISSUE THREAD

**Issue by baticag** [Prunt/RestrictedCreative#39] opened 2018-07-26 02:07 UTC
Demonstrated in the video:
https://www.youtube.com/watch?v=QH-R0yCjdiY

**Comment by Prunt** [comment] 2018-08-03 07:01
What Spigot/Paper version are you using? I tested it on Spigot 1.12.2 with RC 1.15.2 and couldn't reproduce the bug.

**Comment by Prunt** [comment] 2018-08-13 03:50
I'm going to close this for now. If you have additional information to give me, feel free to reopen.

**Closed by Prunt** 2018-08-13 03:50 UTC
Labels: need info
