### ISSUE TITLE
Issues - Suggestion

### ISSUE THREAD

**Issue by CryptoMorin** [Prunt/RestrictedCreative#9] opened 2017-12-27 09:41 UTC
Hi there,
Well it's me again. We bought this plugin a few days ago and it's already updated to latest version.
(If you're wondering why my name isn't in your purchase list it's because the owner bought the plugin not me. If you want to look for the name... His name is something like "Koolaid" in here.)
Here is what i found:

**Issues**

- Duplicated message when opening inventory using CommandNPC right-clicking on NPCs. (I'm not sure but this can be CommandNPC problem)
It also happens when you right-click a painting. (I don't even know why it should send a message for paintings...)
- Permissions for opped players doesn't seem to work at all. Are the permission set to false by default?
I even disabled permissions in config.yml
 permissions:
    enabled: false
    list:

- (Nevermind just found out you already noticed and mentioned in the plugin page) If you put a flower in a flower pot and break the block under it, it'll drop the flower. Same when using falling anvils.
- If you break a redstone or diamond ore (Using pickaxe in survival) it'll still drop EXP.

**Suggestion**
- Some players complain that why Creative Inventory resets when they logout. Can you add an option in config so we can disable that?
- Just a small thing... You can ignore this, not even a problem... But don't you think it's better you keep the Configuration File guide in the Wiki section and remove it from the config header? I mean it's totally okay if you disagree. Your opinion!

**Comment by Prunt** [comment] 2018-01-05 20:16
Sorry for the late reply, but here are my answers:
1. The duplicated message is sent because the `PlayerInteractEntityEvent` is fired twice for a single click. I don't know why it does that, but I'll see if I can do anything.
2. Bypass permissions are set to `false` by default, you'll have to give them separately. The permissions section in config is for giving special permissions (or taking them away) for players in creative mode.
3. It shouldn't drop the flower itself, the plugin page message is only about a visual glitch. Are you able to pass the flower from creative mode to survival mode by destroying the block underneath? Falling anvils shouldn't drop on the ground as an item as well. Can you post the exact steps to reproduce the problem?
4. Thanks for reporting that, it'll be fixed in the next version.
5. Since I haven't been able to find a way to efficiently store inventories to a database, I'm forced to remove creative mode and return player's their survival items when they log out. I added it to my TO-DO list and I'll get back to it someday.
6. You're probably right, but I haven't got around to it yet. It's easier to toss the explanation right along with the option itself. I'll add that too to my list.

**Comment by CryptoMorin** [comment] 2018-01-06 07:53
About the InteractEvent you're right one for main and other for offhand as some devs still need that. I figured it out a week ago when using `EquipmentSlots` in `PlayerInteractEvent`. I don't know why but for some odd reasons it doesn't do the duplicated message for clicking air.

And oh well the permissions... i just noticed that two days ago from plugin.yml.

The flower pots was a bug in the public server. I took the plugin and placed it in a fresh server without any other plugins to try it out again. It worked fine. Probably another plugin... oh well...
But a problem... when clicking the flower pot without anything in your hand it'll send a duplicated message again. I guess do the same trick you did for the first issue? (It's fine when holding a block or something else in your hand as it's only one hand placing the block) Second is that if you try to put a flower in the flower pot it'll send a message but it'll still place the flower!

Thanks for fixing the other bugs!

**Comment by Prunt** [comment] 2018-01-06 15:34
I'll have to find a better way to handle the duplicate messages. I'll think of something when I start developing the next version.

I'm aware that it'll still place the flower, but other players shouldn't be able to see it. I can't do anything to prevent that.

**Comment by Prunt** [comment] 2018-01-15 08:52
1.12.5 will fix the duplicate messages once and for all.

**Closed by Prunt** 2018-01-15 08:52 UTC
